version: '3.5'
services:
  taskForce.uploader.mongo:
    image: mongo
    restart: always
    container_name: taskForce.uploader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: taskForce-uploader

    ports:
      - 27018:27017

    volumes:
      - taskForce.mongo.uploader:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskForce-uploader --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  taskForce.uploader.mongo.ui:
    image: mongo-express
    restart: always
    container_name: taskForce.uploader.mongo.ui
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@taskForce.uploader.mongo:27017/

volumes:
  taskForce.mongo.uploader:
